### ISSUE TITLE
Reach `abstract` field

### ISSUE THREAD

**Issue by ngottlieb** [AmericanWhitewater/nwi-data-tool#3]
@mojodna -- I need the `reach.abstract` column for the map viewer. I'm not sure if it makes sense for you to regenerate the style with it now or if I should just code as though it's there (stub it out maybe) and wait till we're working off the API? Let me know what makes the most sense here, I'm fine either way.

**Comment by sethfitz** [comment]
This was added in 38eae44b5e0a7d3c0af8fee89b94cbab579b9df2
